# Generated by Django 2.2 on 2019-04-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('parallel', models.CharField(default='A', max_length=1)),
            ],
            options={
                'unique_together': {('name', 'parallel')},
            },
        ),
    ]
